#ifndef STM_ESP_HOSTED_PRIVATE_H
#define STM_ESP_HOSTED_PRIVATE_H
#include "stm_esp_hosted.h"
struct esp_hosted_context {
    esp_hosted_config_t config;
    esp_hosted_info_t info;
    esp_hosted_rx_fn receive;
    esp_hosted_link_fn link;
    void *user;
    uint16_t sequence;
    uint32_t uid;
    uint32_t response_uid;
    uint16_t response_id;
    uint8_t response_data[512];
    size_t response_length;
    esp_hosted_version_t version;
    uint8_t mac[6];
    uint8_t initialized;
    uint8_t negotiated;
    uint8_t connected;
    uint8_t wifi_initialized;
    uint8_t wifi_started;
    uint8_t wifi_mode;
    uint8_t scan_pending;
    uint8_t scan_done;
    uint32_t last_disconnect_reason;
    eh_wifi_reconnect_config_t reconnect_config;
    uint32_t reconnect_since;
    uint32_t reconnect_delay;
    uint16_t reconnect_attempts;
    uint8_t reconnect_armed;
    uint8_t reconnect_waiting;
    uint8_t connect_pending;
    eh_wifi_event_fn wifi_event;
    void *wifi_event_user;
    eh_wifi_ap_link_fn ap_link;
    void *ap_link_user;
    uint8_t ap_up;
    eh_wifi_ap_rx_fn ap_receive;
    void *ap_user;
    uint8_t response_ready;
};
#endif
